### ISSUE TITLE
Unable to crawl users at the moment, could any expert please help take a look? 

### ISSUE THREAD

**Issue by kcxg** [AmirRedHat/LinkedIn-Crawler#1]
It was still working a few days ago.

**Comment by AmirRedHat** [comment]
Hey , can you check your ip in linkedin ? Maybe they are blocking you.
You can also run test step by step.

**Comment by kcxg** [comment]
i can log in to the website directly.    Users cannot be found at this location in the screenshot.
![image](https://github.com/AmirRedHat/LinkedIn-Crawler/assets/31840413/a5bdfdd4-4a3c-40a8-87fa-5ceb851efad4)

**Comment by kcxg** [comment]
@AmirRedHat  Can you please help me take a look?

**Comment by AmirRedHat** [comment]
> rs cannot be found at thi

In this location if 'users' is none then driver cannot find an html element  by a class attribute 'entity-result__item'

**Comment by AmirRedHat** [comment]
> @AmirRedHat Can you please help me take a look?

your connection can effect on loading elements in browser. you can change sleeps and then try again. i will check this section.
